### ISSUE TITLE
Password for ruff

### ISSUE THREAD

**Issue by phodina** [rufferson/pureos-pinephone#1]
Could you please provide password for ruff to unlock the rootfs?

**Comment by rufferson** [comment]
Do you mean for root? root account's password is locked 
```
purism@pureos:~$ sudo grep root /etc/shadow
root:!*:18600:0:99999:7::1:
```
not sure what else could be locked there but tbh I didn't regenerate the image for quite a while now, just using the one I created several months ago and simply pulling the updates with `sudo apt update` + `sudo apt upgrade`, and from time to time (like yesterday) running `./update_kernel.sh` to pull the latest one.

**Comment by rufferson** [comment]
maybe it was about luks password to rootfs? that was default 123456 (same as user pass). I'll close this but fill free to create a new and more descriptive one :)
