### ISSUE TITLE
build script  mount error: /home/steve/purepp/sd: unknown filesystem type 'crypto_LUKS'.

### ISSUE THREAD

**Issue by delta1071** [rufferson/pureos-pinephone#2]
Hi,
I'm trying to build a pureos img that is bootable by a Pinephone 64 3GB. The script executes properly until line 72 (I think), where the above mount error is reported. I have spent hours trying to figure out exactly how to create a random loop device with one luks encrypted partition and one unencrypted boot partition. Are there some commands that I could add to your script to get past this error? I appreciate any input you can provide.

Steve Silvi

**Comment by rufferson** [comment]
Oh, I need to try to rebuild it, purism introduced luks FDE a while ago but it slipped my attention that it affects build script.
In general you'd need to use cryptsetup tools (as with normal luks partition) on loopback device, but let me try and see exact command sequence for the mount.

**Comment by delta1071** [comment]
Thank you for responding so quickly. I'm currently waiting for the Librem 5 I ordered to be delivered and would like to preview PureOS before it arrives. I appreciate the effort you are making to help me!

**Comment by rufferson** [comment]
sorry for a long silence, I was trying to download fresh image several days but it was failing, so i gave up. Now I've tried again and it worked. So I'll commit a change with luks support HOWEVER I will also change to new ATF (crust-firmware) to get power-management working. And i will be booting this image tomorrow morning (it's midnight now). so it's not tested yet.
